---
- name: 7zip
  hosts: win
  tasks:
  - name: Install 7zip 
    win_package:
      path: C:\Temp\7z2107-x64.exe
      product_id: 7-Zip
      arguments: /S
      state: present
    become: yes
    become_method: runas
    vars:
      ansible_become_user: Administrator
      
