---
- name: manage windows servers
  hosts: win
  become: false
  tasks:
  - name: create dir
    win_file:
      path: C:\Temp\folder\sina\2
      state: directory
  - name: allow user
    win_acl:
      path: C:\Temp\folder\sina\2
      user: user
      rights: Read,Write
      type: allow
      state: present    
