---
- name: Install software
  hosts: win
  gather_facts: false
  tasks:
    - name: Install Splunk Forwarder
      win_chocolatey:
        name: splunk-universalforwarder
        state: present 
    - name: Copy a single file
      win_copy:
        src: /home/deploymentclient.conf
        dest: C:\Program Files\SplunkUniversalForwarder\etc\system\local\
    - name: Restart a service
      tags: service
      ansible.windows.win_service:
        name: SplunkForwarder
        state: restarted

